# Generated by Django 3.0.5 on 2021-05-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RUC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rucEmpresa', models.CharField(max_length=11, unique=True, verbose_name='RUC')),
                ('nombreEmpresa', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estado', models.CharField(max_length=8, verbose_name='Estado')),
                ('tipoEmpresa', models.CharField(max_length=50, verbose_name='Tipo')),
                ('rutaRuc', models.CharField(max_length=80, verbose_name='Ruta')),
                ('titular', models.CharField(max_length=50, verbose_name='Titular')),
                ('identificacion', models.IntegerField(max_length=8, unique=True, verbose_name='DNI')),
            ],
        ),
    ]
