# Generated by Django 3.0.5 on 2021-05-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RUC', '0002_auto_20210526_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruc',
            name='estado',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='ruc',
            name='identificacion',
            field=models.IntegerField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='ruc',
            name='nombreEmpresa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ruc',
            name='rucEmpresa',
            field=models.IntegerField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='ruc',
            name='rutaRuc',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='ruc',
            name='tipoEmpresa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ruc',
            name='titular',
            field=models.CharField(max_length=50),
        ),
    ]
