# Generated by Django 3.0.5 on 2021-05-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RUC', '0005_auto_20210526_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruc',
            name='identificacion',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
